### PR TITLE
Added version_normalized

### PR DESCRIPTION
**Pull request by edgardmessias**
Example: https://packagist.org/p/yiisoft/yii2$255da1f97f1cb80c00cc01097f7c7d7df161f7c5327233e3ed62a624d6950b89.json

Current:
```json
"bower-asset/moment": {
    "9999999-dev": {
        "version": "9999999-dev",
    },
},
```
Propose:
```json
"bower-asset/moment": {
    "dev-master": {
        "version": "dev-master",
        "version_normalized": "9999999-dev",
    },
},
```

### CODE REVIEW

**Comment by hiqsol** [comment]
Is it okay for composer?
What is a reason of this change? Nobody cares of these internal versions.

**Comment by edgardmessias** [comment]
> Is it okay for composer?

Yes, composer use version_normalized for For comparison, if it is present.

> What is a reason of this change? Nobody cares of these internal versions.

[Packagist](https://packagist.org/) and [Wordpress Packagist](https://wpackagist.org/) have version_normalized.

You can see, for example, the [moment](https://asset-packagist.org/package/search?query=bower-asset%2Fmoment) does not have the dev-master version.

With the change, dev-version is displayed, and versions are with shorter names (Ex.: 2.18.1.0 => 2.18.1)

**Comment by SilverFire** [comment]
The longer list is before the PR, the shorter - after. Conclusion - the PR affects system a lot and I don't think it should be accepted. Sorry

screencapture-asset-packagist-org-package-search-1493302463645

=======

screencapture-local-asset-packagist-org-package-search-1493302453929

**Comment by edgardmessias** [comment]
Sorry, this is my screenshot:

screenshot

**Comment by edgardmessias** [comment]
See in the composer source:

[ArrayDumper](https://github.com/composer/composer/blob/e3a23c0047b462f1a443cdb56d3c310a9e4c3b37/src/Composer/Package/Dumper/ArrayDumper.php#L41)
[InstallationManager](https://github.com/composer/composer/blob/e3a23c0047b462f1a443cdb56d3c310a9e4c3b37/src/Composer/Installer/InstallationManager.php#L271)
[ArrayLoader](https://github.com/composer/composer/blob/e3a23c0047b462f1a443cdb56d3c310a9e4c3b37/src/Composer/Package/Loader/ArrayLoader.php#L50)


If version_normalized is not set, composer call VersionParse.
You can see examples here: [VersionParserTest](https://github.com/composer/semver/blob/master/tests/VersionParserTest.php#L52)

This change brings more composer performance on the client side

**Comment by SilverFire** [comment]
Is your screenshot from production asset-packagist.org?

**Comment by edgardmessias** [comment]
No, my local machine.

**Comment by SilverFire** [comment]
Ehm... Ok, let me re-check it :)

**Comment by SilverFire** [comment]
Thank you :)

**Pull request merged**
